name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt install fasm make zip
        
    - name: Build
      run: |
        make
        rm *.s
        rm *.inc
        rm Makefile
        zip aceutils.zip *
      
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: aceutils-artifact
        path: aceutils.zip
      
  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: [ build ]

    steps:
      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: aceutils-artifact

      - name: Update Latest Release
        uses: andelf/nightly-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: latest-release
          name: 'Latest Release'
          body: |
            Automated latest release for commit ${{ github.sha }}.
          files: |
            ./aceutils.zip
