name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install dependencies
      run: |
        sudo apt install fasm build-essential
        
    - name: Build
      run: |
        g++ -o rebuild rebuild.cpp && ./rebuild build
        rm *.s
        rm *.inc
        rm Makefile
        chmod +x *
        chmod -x README.md
        chmod -x LICENSE
        mkdir ../_aceutils
        mv * ../_aceutils
        mv ../_aceutils ./aceutils
        tar czvf aceutils.tar.gz aceutils
      
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: aceutils-artifact
        path: aceutils.tar.gz
      
  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: [ build ]

    steps:
      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: aceutils-artifact

      - name: Update Latest Release
        uses: andelf/nightly-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: latest-release
          name: 'Latest Release'
          body: |
            Automated latest release for commit ${{ github.sha }}.
          files: |
            ./aceutils.tar.gz
